GET https://api.via-dolorosa.ru/rc/90459/full_info
Accept: application/json

###

GET https://api.via-dolorosa.ru/rc/90459/status
Accept: application/json

###

POST https://api.via-dolorosa.ru/rc/90459/custom_phase_program
Accept: application/json
